export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';


export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_FAILURE = 'FETCH_SERVICE_FAILURE';

export const SAVE_SERVICE_INIT = 'SAVE_SERVICE_INIT';
export const SAVE_SERVICE_REQUEST = 'SAVE_SERVICE_REQUEST';
export const SAVE_SERVICE_FAILURE = 'SAVE_SERVICE_FAILURE';
export const SAVE_SERVICE_SUCCESS = 'SAVE_SERVICE_SUCCESS';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';


export const ADD_SERVICE = 'ADD_SERVICE';
export const DEL_SERVICE = 'DEL_SERVICE';
export const SEL_SERVICE = 'SEL_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';