export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CLEAR_SEARCH_FIELD = 'CLEAR_SEARCH_FIELD';

