export const ADD_SERVICE = 'ADD_SERVICE';
export const DEL_SERVICE = 'DEL_SERVICE';
export const SEL_SERVICE = 'SEL_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const ADDEDIT_SERVICE = 'ADDEDIT_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';