export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const APPEND_CATALOG = 'APPEND_CATALOG';


export const LOADMORE_REQUEST = 'LOADMORE_REQUEST';
export const LOADMORE_FAILURE = 'LOADMORE_FAILURE';
export const LOADMORE_SUCCESS = 'LOADMORE_SUCCESS';
export const LOADMORE_REFRESH = 'LOADMORE_REFRESH';


export const FETCH_TOPSALES_REQUEST = 'FETCH_TOPSALES_REQUEST';
export const FETCH_TOPSALES_FAILURE = 'FETCH_TOPSALES_FAILURE';
export const FETCH_TOPSALES_SUCCESS = 'FETCH_TOPSALES_SUCCESS';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const CHANGE_PRODUCT_COUNT = 'CHANGE_PRODUCT_COUNT';
export const CHANGE_PRODUCT_SIZE = 'CHANGE_PRODUCT_SIZE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_TO_CART = 'SET_TO_CART';
export const DEL_TO_CART = 'DEL_TO_CART';
export const LOAD_CART = 'LOAD_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';
export const POST_ORDER_CLEAR = 'POST_ORDER_CLEAR';


export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const UP_SEARCH = 'UP_SEARCH';
export const SET_SEARCH = 'SET_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
