export const UPTO_CATALOG_REQUEST = 'UPTO_CATALOG_REQUEST';
export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const UPTO_CATALOG_FAILURE = 'UPTO_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const UPTO_CATALOG_SUCCESS = 'UPTO_CATALOG_SUCCESS';

export const FETCH_TOPSALES_REQUEST = 'FETCH_TOPSALES_REQUEST';
export const FETCH_TOPSALES_FAILURE = 'FETCH_TOPSALES_FAILURE';
export const FETCH_TOPSALES_SUCCESS = 'FETCH_TOPSALES_SUCCESS';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const CHANGE_PRODUCT_COUNT = 'CHANGE_PRODUCT_COUNT';
export const CHANGE_PRODUCT_SIZE = 'CHANGE_PRODUCT_SIZE';

export const ADD_TO_CARD = 'ADD_TO_CARD';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';



export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';


export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_FAILURE = 'FETCH_SERVICE_FAILURE';

export const SAVE_SERVICE_INIT = 'SAVE_SERVICE_INIT';
export const SAVE_SERVICE_REQUEST = 'SAVE_SERVICE_REQUEST';
export const SAVE_SERVICE_FAILURE = 'SAVE_SERVICE_FAILURE';
export const SAVE_SERVICE_SUCCESS = 'SAVE_SERVICE_SUCCESS';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';


export const ADD_SERVICE = 'ADD_SERVICE';
export const DEL_SERVICE = 'DEL_SERVICE';
export const SEL_SERVICE = 'SEL_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';